//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_DB_8_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int КодПоставщика { get; set; }
        public Nullable<System.DateTime> ДатаДоговора { get; set; }
        public int НомерДоговора { get; set; }
        public string Поставщик { get; set; }
    }
}
