//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_DB_8_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Договоры
    {
        public Договоры()
        {
            this.Поставлено = new HashSet<Поставлено>();
        }
    
        public int НомерДоговора { get; set; }
        public Nullable<System.DateTime> ДатаДоговора { get; set; }
        public int КодПоставщика { get; set; }
        public string Комментарий { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
        public virtual ICollection<Поставлено> Поставлено { get; set; }
    }
}
