//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_DB_8_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставщики
    {
        public Поставщики()
        {
            this.Договоры = new HashSet<Договоры>();
        }
    
        public int КодПоставщика { get; set; }
        public string Адрес { get; set; }
        public string Примечание { get; set; }
    
        public virtual ICollection<Договоры> Договоры { get; set; }
        public virtual ФизическиеЛица ФизическиеЛица { get; set; }
        public virtual ЮридическиеЛица ЮридическиеЛица { get; set; }
    }
}
