//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp_DB_8_Lab
{
    using System;
    using System.Collections.Generic;
    
    public partial class ФизическиеЛица
    {
        public int КодПоставщика { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string НомерСвидетельства { get; set; }
    
        public virtual Поставщики Поставщики { get; set; }
    }
}
